version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:v1.10.1
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6335:6335"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6335
