# -*- coding: utf-8 -*-
"""pdf_chunk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPFx7HzUmf_nhGahLpPndACHHKRnRlgM
"""

!pip install pymupdf==1.27.2

import pymupdf as fitz
import re


HEADER_PATTERNS = [
    r"NORMAS LEGALES",
    r"El Peruano",
    r"Martes.*20\d\d",
    r"^\d+$"
]

FOOTER_PATTERNS = [
    r"Texto según el",
]


def is_header_or_footer(text):

    text = text.strip()

    for pattern in HEADER_PATTERNS:

        if re.search(pattern, text, re.IGNORECASE):
            return True

    return False


def clean_text(text):

    text = text.replace("\xa0", " ")

    text = re.sub(r"\s+", " ", text)

    return text.strip()


def extract_document_structure(pdf_path):

    doc = fitz.open(pdf_path)

    document = []

    for page in doc:
      if page.number == 0:

        crop = fitz.Rect(
            page.rect.x0,
            350,          # ajustar una sola vez
            page.rect.x1,
            page.rect.y1
        )
        page.set_cropbox(crop)

      page_dict = page.get_text("dict")

      middle = page.rect.width / 2

      left_blocks = []
      right_blocks = []

      for block in page_dict["blocks"]:

            if block["type"] != 0:
                continue

            spans = []

            for line in block["lines"]:

                for span in line["spans"]:

                    spans.append(span)

            if len(spans) == 0:
                continue

            text = " ".join(
                span["text"]
                for span in spans
            )

            text = clean_text(text)

            if text == "":
                continue

            if is_header_or_footer(text):
                continue

            x0, y0, x1, y1 = block["bbox"]

            item = {
                "bbox": block["bbox"],
                "text": text,
                "font_size": max(s["size"] for s in spans),
                "flags": max(s["flags"] for s in spans)
            }

            if x0 < middle:

                left_blocks.append(item)

            else:

                right_blocks.append(item)

      left_blocks.sort(key=lambda b: b["bbox"][1])
      right_blocks.sort(key=lambda b: b["bbox"][1])

      document.extend(left_blocks)
      document.extend(right_blocks)

    return document

import re


TITLE_RE = re.compile(r"^T[IÍ]TULO", re.I)

CAP_RE = re.compile(r"^CAP[IÍ]TULO", re.I)

SUBCAP_RE = re.compile(r"^SUBCAP[IÍ]TULO", re.I)

ARTICLE_RE = re.compile(
    r"^ART[IÍ]CULO\s+(\d+)",
    re.I
)

def parse_document(blocks):

    titulo = None

    capitulo = None

    subcapitulo = None

    articles = []

    current = None

    for block in blocks:

        text = block["text"]

        if TITLE_RE.match(text):

            titulo = text

            capitulo = None

            subcapitulo = None

            continue

        if CAP_RE.match(text):

            capitulo = text

            subcapitulo = None

            continue

        if SUBCAP_RE.match(text):

            subcapitulo = text

            continue

        m = ARTICLE_RE.match(text)

        if m:

            if current is not None:

                current["texto"] = current["texto"].strip()

                articles.append(current)

            current = {

                "titulo": titulo,

                "capitulo": capitulo,

                "subcapitulo": subcapitulo,

                "articulo": text,

                "texto": ""

            }

            continue

        if current is not None:

            current["texto"] += "\n" + text

    if current is not None:

        current["texto"] = current["texto"].strip()

        articles.append(current)

    return articles

import re


def clean_article(article):

    txt = article["texto"]

    txt = re.sub(
        r"\(Texto según.*?\)",
        "",
        txt,
        flags=re.DOTALL
    )

    txt = re.sub(
        r"NORMAS LEGALES",
        "",
        txt
    )

    txt = re.sub(
        r"El Peruano",
        "",
        txt
    )

    txt = re.sub(
        r"\n{2,}",
        "\n",
        txt
    )

    article["texto"] = txt.strip()

    return article

pdf_path = "/content/RESOLUCIÓN N_º 058-2023-SUNASS-CD-5-36.pdf"
blocks = extract_document_structure(pdf_path)

articles = parse_document(blocks)

articles = [
    clean_article(a)
    for a in articles
]

print(articles)