# Traducción de códigos de EMAPA a texto legible (conocimiento de dominio).
# Fuente: data_22_40.xlsx (hojas tipoestlectura, tipoestservicio, tipoestmedidor,
# tarifas, tipopromedio).
INDICADORES_TARJETA_LECTURA = {
    "estadolectura": {
        "000": "LECTURA NORMAL",
        "001": "CONSUMO EXCESIVO",
        "002": "LECTURAS IGUALES",
        "003": "NO REGISTRO CONSUMO Y/O LECTURA",
        "004": "CONSUMO NEGATIVO",
        "005": "MEDIDOR NUEVO",
        "006": "LECTURA ULTIMA MENOR",
        "007": "CONEXION CERRADO CON LECTURA",
        "008": "CONSUMO ATIPICO",
        "009": "LECTURA NO VALIDA X DIAS",
        "010": "CONSUMO MENOR AL PROMEDIO",
        "011": "CONSUMO DOBLE AL PROMEDIO",
        "998": "PROMEDIO X IMPEDIMENTO",
        "999": "NO REGISTRO LECTURA",
    },
    "estadoservicio": {
        "001": "OPERATIVO CON SERVICIO-ACTIVO",
        "002": "OPERATIVO SIN SERVICIO-CORTADO",
        "003": "CLANDESTINO Y/O CLAUSURADO",
        "004": "LEVANTADO",
        "005": "OPERATIVO SIN SERVICIO-A SOLICITUD",
        "006": "INCOBRABLE",
        "007": "QUEBRADO",
        "008": "ANULADO",
        "009": "CONEXION PROYECTADA",
    },
    "estadomed": {
        "000": "[NINGUNO]",
        "001": "BUENA CONDICION",
        "002": "LUNA ROTA",
        "003": "DESTRUIDO",
        "004": "MEDIDOR ROBADO",
        "005": "PARALIZADO",
        "006": "NUBLADO",
        "007": "INVERTIDO POR EL CLIENTE",
        "008": "CAMBIADO 1RA. LECTURA",
        "009": "RETIRADO-NO EXISTE-PROMEDIDADO",
        "010": "CAJA SIN TAPA",
        "011": "SIN CAJA  NI TAPA",
        "012": "MEDIDOR CON VANDALISMO",
        "013": "LUNA OPACA",
        "014": "CAJA  SUCIA",
        "015": "CAJA INUNDADA",
        "016": "CAJA PROFUNDA",
        "017": "MEDIDOR INTERIOR DEL PREDIO",
        "018": "NRO DE MEDIDOR INCORRECTO",
        "019": "ENTERRADO",
        "020": "TAPA TRABADA",
        "021": "IMPEDIMENTO TEMPORAL",
        "022": "SERIE NO LEGIBLE",
        "023": "CASA DESOCUPADA/DESHABITADA",
        "024": "CAJA EMPOTRADA",
        "025": "TERRENO LIBRE",
        "026": "CASA EN CONSTRUCCIÓN",
        "027": "SERVICIO CORTADO",
        "028": "INVERTIDO POR OTROS",
        "029": "FUGA EN CAJA",
        "030": "MEDIDOR AVERIADO",
        "031": "TAPA ROTA",
        "032": "FUGA ANTES DEL MEDIDOR",
        "033": "FUGA DESP. DEL MEDIDOR",
        "034": "CABEZAL SUELTO",
        "035": "SIN MEDIDOR",
        "050": "INOPERATIVO",
        "060": "REINSTALADO POR BCO MEDIDOR",
        "070": "FUERA DE RUTA",
        "090": "INSTALADO POR BAC MEDIDOR",
        "091": "INSTALADO POR CATASTRO CONEXIO",
        "092": "MEDIDOR MANIPULADO",
    },
    # catetar: código de categoría tarifaria -> nombre. Del Excel se derivan
    # combinando codsuc+catetar, por eso hay repetidos (misma categoría distinta
    # sucursal); aquí se consolida el nombre único por código.
    "catetar": {
        "001": "DOMESTICO",
        "002": "DOM ANEXOS",
        "015": "COMERCIAL",
        "022": "INDUSTRIAL",
        "024": "ESTATAL",
        "026": "SOCIAL",
        "027": "SOCIAL",
        "101": "DOMESTICO BENEF",
    },
    "tipopromedio": {
        "0": "MEDIDO",
        "1": "ASIGNADO",
        "2": "PROMEDIADO",
    },
}
